image:
  file: Dockerfile

tasks:
  - init: echo "✅ Python playground ready"
    command: cd workspace && jupyter lab notebooks/demo.ipynb --no-browser --ip=0.0.0.0 --port=8888 --NotebookApp.token=''

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-python.vscode-pylance
    - donjayamanne.python-environment-manager

ports:
  - port: 8888
    onOpen: "open-preview"
