# Use your custom Dockerfile
image:
  file: Dockerfile

# Tasks to run when the workspace starts
tasks:
  - init: echo "✅ Environment setup complete"
    command: cd workspace && jupyter lab notebooks/demo.ipynb --no-browser --ip=0.0.0.0 --port=8888

# Configure VS Code extensions
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-python.vscode-pylance
    - donjayamanne.python-environment-manager

# Ports to expose for the Jupyter Lab UI
ports:
  - port: 8888
    onOpen: "open-preview"
