# Use custom Dockerfile
image:
  file: Dockerfile

# Tasks to run when the workspace starts
tasks:
  - init: echo "✅ Python environment is ready!"
    command: jupyter lab --no-browser --ip=0.0.0.0 --port=8888

# Configure VS Code Extensions
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-python.vscode-pylance
    - donjayamanne.python-environment-manager

# Ports to expose (Jupyter Lab runs on 8888)
ports:
  - port: 8888
    onOpen: open-preview
